import pandas as pd
import bisect

# 假设df是原始DataFrame，包含time、mb、dev、bank列
# 确保time列为datetime类型
df['time'] = pd.to_datetime(df['time'])

result_dfs = []

# 按分组处理数据
for (mb, dev, bank), group in df.groupby(['mb', 'dev', 'bank']):
    # 按时间排序当前分组的数据
    sorted_group = group.sort_values('time')
    sorted_times = sorted_group['time'].tolist()
    
    counts = []
    for t in sorted_group['time']:
        # 计算时间窗口左边界
        left = t - pd.Timedelta(hours=24)
        # 使用二分查找确定窗口内的记录数
        left_pos = bisect.bisect_left(sorted_times, left)
        right_pos = bisect.bisect_left(sorted_times, t)
        count = right_pos - left_pos
        counts.append(count)
    
    # 添加新列到当前分组
    sorted_group = sorted_group.copy()
    sorted_group['count_24h'] = counts
    result_dfs.append(sorted_group)

# 合并所有分组并恢复原始索引顺序
df_result = pd.concat(result_dfs).sort_index()

print(df_result)
Traceback (most recent call last):
  File "/home/liangfei/Workspace-WYQ/HBM/data_re.py", line 6, in <module>
    df = pd.read_csv('hbm_del.csv')
  File "/home/liangfei/anaconda3/envs/EXP-WYQ/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/liangfei/anaconda3/envs/EXP-WYQ/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
  File "/home/liangfei/anaconda3/envs/EXP-WYQ/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1968, in read
    df = DataFrame(
  File "/home/liangfei/anaconda3/envs/EXP-WYQ/lib/python3.10/site-packages/pandas/core/frame.py", line 778, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/home/liangfei/anaconda3/envs/EXP-WYQ/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 443, in dict_to_mgr
    arrays = Series(data, index=columns, dtype=object)
  File "/home/liangfei/anaconda3/envs/EXP-WYQ/lib/python3.10/site-packages/pandas/core/series.py", line 490, in __init__
    index = ensure_index(index)
  File "/home/liangfei/anaconda3/envs/EXP-WYQ/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 7647, in ensure_index
    return Index(index_like, copy=copy, tupleize_cols=False)
  File "/home/liangfei/anaconda3/envs/EXP-WYQ/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 565, in __new__
    arr = sanitize_array(data, None, dtype=dtype, copy=copy)
  File "/home/liangfei/anaconda3/envs/EXP-WYQ/lib/python3.10/site-packages/pandas/core/construction.py", line 654, in sanitize_array
    subarr = maybe_convert_platform(data)
  File "/home/liangfei/anaconda3/envs/EXP-WYQ/lib/python3.10/site-packages/pandas/core/dtypes/cast.py", line 138, in maybe_convert_platform
    arr = lib.maybe_convert_objects(arr)
  File "lib.pyx", line 2538, in pandas._libs.lib.maybe_convert_objects
TypeError: Cannot convert numpy.ndarray to numpy.ndarray

Traceback (most recent call last):
  File "/home/liangfei/Workspace-WYQ/HBM/lstm_test.py", line 57, in <module>
    hstory = model.fit(
  File "/home/liangfei/anaconda3/envs/YYTEXP/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/liangfei/anaconda3/envs/YYTEXP/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
ValueError: Exception encountered when calling LSTMCell.call().

Dimensions must be equal, but are 15 and 12 for '{{node sequential_1/lstm_1/lstm_cell_1/MatMul}} = MatMul[T=DT_FLOAT, grad_a=false, grad_b=false, transpose_a=false, transpose_b=false](sequential_1/lstm_1/strided_slice_2, sequential_1/lstm_1/lstm_cell_1/Cast/ReadVariableOp)' with input shapes: [?,15], [12,256].

Arguments received by LSTMCell.call():
  • inputs=tf.Tensor(shape=(None, 15), dtype=float32)
  • states=('tf.Tensor(shape=(None, 64), dtype=float32)', 'tf.Tensor(shape=(None, 64), dtype=float32)')
  • training=True

Traceback (most recent call last):
  File "/home/liangfei/Workspace-WYQ/HBM/lstm_test.py", line 83, in <module>
    model = Sequential([
  File "/home/liangfei/anaconda3/envs/YYTEXP/lib/python3.10/site-packages/keras/src/models/sequential.py", line 76, in __init__
    self._maybe_rebuild()
  File "/home/liangfei/anaconda3/envs/YYTEXP/lib/python3.10/site-packages/keras/src/models/sequential.py", line 149, in _maybe_rebuild
    self.build(input_shape)
  File "/home/liangfei/anaconda3/envs/YYTEXP/lib/python3.10/site-packages/keras/src/layers/layer.py", line 229, in build_wrapper
    original_build_method(*args, **kwargs)
  File "/home/liangfei/anaconda3/envs/YYTEXP/lib/python3.10/site-packages/keras/src/models/sequential.py", line 195, in build
    x = layer(x)
  File "/home/liangfei/anaconda3/envs/YYTEXP/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/liangfei/anaconda3/envs/YYTEXP/lib/python3.10/site-packages/keras/src/layers/attention/attention.py", line 300, in _validate_inputs
    raise ValueError(
ValueError: Attention layer must be called on a list of inputs, namely [query, value] or [query, value, key]. Received: inputs=(None, 16, 64).
